dataset_config:
  dataset_name: common_voice_sv
  data_dir: data/
  train_filename: common_voice_sv_train_manifest.json
  val_filename: common_voice_sv_val_manifest.json
  to_filter_filename: common_voice_sv_to_filter_manifest.json
  # Caption configs
  text:
    max_seq_length: 256
    tokenizer: berttokenizer # one of berttokenizer, cliptokenizer
  audio:
    sr: 16000
    crop_length: 30
    random_crop: true
    augment: false
    p_noise: 0.3
    p_pitch_shift: 0.4

    
