# dataset_config:
#   dataset_name: common_voice
#   data_dir: data/
#   train_filename: common_voice_train_manifest.json
#   val_filename: common_voice_val_manifest.json
#   to_filter_filename: common_voice_val_manifest.json

  #python apply_filering.py data/common_voice_train_manifest.json

# python apply_filering.py data/syndata_11labs_train_manifest.json

# dataset_config:
#   dataset_name: syndata_elevenlabs
#   data_dir: data/
#   to_filter_filename: syndata_11labs_train_manifest.json

dataset_config:
  dataset_name: combined_data
  data_dir: data/
  to_filter_filename: combined_train_manifest.json

# python apply_filering.py data/combined_train_manifest.json

# dataset_config:
#   dataset_name: syndata_fb
#   data_dir: data/
#   to_filter_filename: syndata_fb_train_manifest.json
  # Caption configs

  # python apply_filering.py data/syndata_fb_train_manifest.json
  text:
    max_seq_length: 256
    tokenizer: berttokenizer # one of berttokenizer, cliptokenizer
  audio:
    sr: 16000
    crop_length: 30
    random_crop: true
    augment: false
    p_noise: 0.3
    p_pitch_shift: 0.4

    
